#! /bin/bash

source ../conf/env

# header protector
[[ -z "${__lib_utils__}" ]] && {
__lib_utils__=a


function log(){
	datetime=$(date +'%Y-%m-%d %H:%M')
	echo "[${datetime}] $0 $@"
}

function input(){
	echo "$@" >> ${INPUT_CHANEL}
}

function record_pid(){
	echo "$?" >> ${RUNNING_PID_FILE}
}



}
