#! /bin/bash

# required
source ${WORK_HOME}/conf/env

# header protector
[[ -z "${__lib_utils__}" ]] && {
__lib_utils__=a


function log(){
	local datetime=$(date +'%Y-%m-%d %H:%M:%S')
	echo "[${datetime}] $0 $@" >> ${LOG_DIR}/log.$(echo ${datetime} | awk '{print $1}')
}

function send(){
	echo "$@" >> ${INPUT_CHANEL}
}

# usage: $(receive)
function receive(){
	for interval in 0.01 0.02 0.05 0.1 0.5 ;do
		read content < <(cat ${OUTPUT_CHANEL} )
		[[ -n ${content} ]] && {
			echo > ${OUTPUT_CHANEL}
			break
		}
		sleep ${interval}
	done
	echo ${content}
}

function record_pid(){
	echo "$?" >> ${RUNNING_PID_FILE}
}

# param: $0 cli | ser
function state_machine_run(){
	local request="hello"
	while true; do
		send ${request}
		# TODO exception $?
		response=$(receive)
		request=$(${1}_action ${response})
	done
}


}

