#! /bin/bash

source ${WORK_HOME}/conf/env
source ${WORK_HOME}/lib/utils

# set -x

function cleanup(){
	log ${RUNNING_PID_FILE}:
	log $(cat ${RUNNING_PID_FILE})
	# 1. clean pids in records
	while read line; do
		kill -9 $line
	done < ${RUNNING_PID_FILE}
	> ${RUNNING_PID_FILE}

	# 2. clean pids of the framework
	local pids=($$)
	pids=(${pids[@]} $(ps -ef | grep "nc ${SERVER_IP}" | grep -v 'grep' | awk '{print $2}') )
	pids=(${pids[@]} $(ps -ef | grep "tailf ${INPUT_CHANEL}" | grep -v 'grep' | awk '{print $2}') )
	for pid in ${pids[@]}; do 
		kill -9 $pid
	done
}

function main(){
	echo "Client starting..."
	# 1. init
	> ${INPUT_CHANEL}
	> ${OUTPUT_CHANEL}
	trap cleanup SIGINT
	# 2. start framework
	while read line ; do
		echo line > ${OUTPUT_CHANEL}
	done < <(nc ${SERVER_IP} ${PORT} < <(tailf ${INPUT_CHANEL}))
	cleanup
}

main "$@"
