#! /bin/bash

source ${WORK_HOME}/conf/env

function main(){

	local app_name=$1
	local role=$2

	source ${app_name}

	if [[ $role == 'cli' ]]; then 
		${WORK_HOME}/inf/client &
	elif [[ $role == 'ser' ]]; then 
		${WORK_HOME}/inf/server &
	fi 
	sleep 5
	${WORK_HOME}/inf/state_machine_run ${app_name} ${role} &

}

main "$@"
