#! /bin/bash

source ${WORK_HOME}/lib/utils

# param: $0 appname cli | ser
function state_machine_run(){
	source $1
	local request="hello"
	while true; do
		request=$($2_request)
		[[ -z  request ]] && request="hello"
		send ${request}
		# TODO exception $?
		response=$(receive)
		request=$(${2}_action ${response})
	done
}

state_machine_run "$@"
