#! /bin/bash

source ${WORK_HOME}/lib/utils

WATCHED_DIR=/tt
COUNT=0

function cli_action(){
	if [[ $1 == "ready" ]]; then
		log $line
		nc ${SERVER_IP} $((++PORT)) < $2
		if [[ $? -eq 0 ]]; then
			log "file transmitted"
		else
			log "file transmit failed"
		fi
	fi
}

function ser_action() {
	if [[ ${1:0:2} == "ci" ]]; then
		nc -l $((++PORT)) > $(awk '{print $2}' <<<"${1}") &
		log "await file command:""nc -l $((++PORT)) > $(awk '{print $2}' <<<"${1}") &"
		sleep 2
		# check nc status, then tell client
		send "ready"
		#echo "ready" > ${INPUT_CHANEL}
	elif [[ $1 == "close" ]]; then
		echo "hell, close"
		exit
	else
		echo "else"
	fi
}


function cli_request() {
	if [[ COUNT -eq 10 ]] ; then
		echo "ci /home/sun/temp"
		COUNT=0
	fi	
}

# server shouldn't push the machine ?!
function ser_request() {
	echo 
}

function file_change_mon(){
	
}

function cli_init() {
	find ${WATCHED_DIR} | tee ${RUNTIME_DIR}/.dir | xargs stat -c %Y > ${RUNTIME_DIR}/.record
	paste ${RUNTIME_DIR}/.dir ${RUNTIME_DIR}/.record > ${RUNTIME_DIR}/dir_record 
	# write to mem
}

